# ä¸€äº›åŸºç¡€è®¾ç½®
baseURL = "https://blog.kawayi.moe"
languageCode = "zh-cn"
title = "MingMoeçš„ç½‘ç»œåšå®¢"

# è®¾ç½®ä¸»é¢˜
theme = "ming"

# è®¾ç½®åˆ†é¡µ
pagination.pagerSize = 6

# è®¾ç½®æ–‡ç« è¾“å‡ºè·¯å¾„
publishDir = "docs"

# è®¾ç½®æ–‡ç« çš„æ°¸ä¹…é“¾æ¥
[permalinks]
  post = "/:year/:monthname/:weekdayname/:title/"

[params]
  title = "æ¬¢è¿æ¥åˆ°å¤§æ˜é…±çš„ç½‘ç»œåšå®¢ğŸ“š"
  subtitle = "ä¸€ä¸ªæŠ€æœ¯å®…çš„ç½‘ç»œåšå®¢â”—|ï½€Oâ€²|â”› ~~"
  mainBackgroundImage = "/Background.webp"
  author = "MingMoe"

# è®¾ç½®åˆ†ç±»æ³•
[taxonomies]
    category = "categories"
    tag = "tags"
    archives = "archives"

# markdownè®¾ç½®
[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = false
    style = "vs"
    tabWidth = 4

  [markup.goldmark]
    [markup.goldmark.renderer]
    # å¯ç”¨ä¸å®‰å…¨ä»£ç 
    unsafe = true

