# ä¸€äº›åŸºç¡€è®¾ç½®
baseURL = "http://blog.kawayi.moe/"
languageCode = "zh-cn"
title = "MingMoeçš„ç½‘ç»œåšå®¢"

# è®¾ç½®ä¸»é¢˜
theme = "ming"

# è®¾ç½®åˆ†é¡µ
paginate = 8

# è®¾ç½®æ–‡ç« çš„æ°¸ä¹…é“¾æ¥
[permalinks]
  post = "/:year/:monthname/:weekdayname/:title/"

[params]
    # ç”¨äºè®¾ç½®å¤§å°æ ‡é¢˜
    Subtitle = "ä¸€ä¸ªæŠ€æœ¯å®…çš„åšå®¢â”—|ï½€Oâ€²|â”› å—·~~"
    Title = "å¤§æ˜é…±çš„ç½‘ç»œæ—¥å¿—ğŸ“š"

    # ç”¨äºè®¾ç½®å›¾ç‰‡
    HeadImage = "/Ming.png"

    # è®¾ç½®èƒŒæ™¯å›¾ç‰‡
    BackgroundImage = "/Background.jpg"

    # è®¾ç½®ä½œè€…åç§°
    Author = "MingMoe"

# è®¾ç½®åˆ†ç±»æ³•
[taxonomies]
    category = "categories"
    tag = "tags"
    archives = "archives"
