# 一些基础设置
baseURL = "https://blog.kawayi.moe/"
languageCode = "zh-cn"
title = "MingMoe的网络博客"

# 设置主题
theme = "ming"

# 设置分页
paginate = 8

# 设置文章输出路径
publishDir = "docs"

# 设置文章的永久链接
[permalinks]
  post = "/:year/:monthname/:weekdayname/:title/"

[params]
  title = "欢迎来到大明朝"
  subtitle = "This is a subtitle!"
  mainBackgroundImage = "/Background.jpg"
  author = "MingMoe"

# 设置分类法
[taxonomies]
    category = "categories"
    tag = "tags"
    archives = "archives"

# markdown设置
[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = false
    style = "vs"
    tabWidth = 4
